name: 'fintech_gold'
version: '1.0.0'
config-version: 2

profile: 'fintech_gold'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  fintech_gold:
    staging:
      +materialized: view
    dimensions:
      +materialized: table
    facts:
      +materialized: table
    marts:
      +materialized: table
